//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsReceivable
    {
        public long AccountsReceivableId { get; set; }
        public long AccountsReceivableIdLocal { get; set; }
        public short LocationId { get; set; }
        public short TypeDoc { get; set; }
        public long CustomerId { get; set; }
        public long InvoiceId { get; set; }
        public long DocNumber { get; set; }
        public System.DateTime Registration { get; set; }
        public System.DateTime Expiration { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountPaid { get; set; }
        public string Observation { get; set; }
        public string StatusAccounts { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string Workstation { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
