//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosingCashierTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClosingCashierTable()
        {
            this.ClosingCashierLine = new HashSet<ClosingCashierLine>();
        }
    
        public long ClosingCashierId { get; set; }
        public long ClosingCashierIdLocal { get; set; }
        public short LocationId { get; set; }
        public int EmissionPointId { get; set; }
        public int UserId { get; set; }
        public System.DateTime ClosingCashierDate { get; set; }
        public string Type { get; set; }
        public long ClosingCashierIdParent { get; set; }
        public decimal OpeningAmount { get; set; }
        public string Authorization { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string Workstation { get; set; }
        public Nullable<int> ReasonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClosingCashierLine> ClosingCashierLine { get; set; }
        public virtual Location Location { get; set; }
        public virtual EmissionPoint EmissionPoint { get; set; }
    }
}
