//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountCashMoney
    {
        public long CountCashId { get; set; }
        public int Sequence { get; set; }
        public int SecLineMoney { get; set; }
        public string DenominationType { get; set; }
        public decimal Denomination { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual CountCashLine CountCashLine { get; set; }
    }
}
