//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public long CustomerAddressId { get; set; }
        public long CustomerAddressIdLocal { get; set; }
        public long CustomerId { get; set; }
        public int Sequence { get; set; }
        public string Address { get; set; }
        public string AddressReference { get; set; }
        public string Coordinates { get; set; }
        public string Telephone { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string Workstation { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
