//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCardTemplateLine
    {
        public long GiftCardTemplateId { get; set; }
        public int Sequence { get; set; }
        public long ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string StatusLine { get; set; }
    
        public virtual GiftCardTemplateTable GiftCardTemplateTable { get; set; }
        public virtual Product Product { get; set; }
    }
}
