//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCardBlockLine
    {
        public long GiftCardBlockId { get; set; }
        public int Sequence { get; set; }
        public long GiftCardNumberStart { get; set; }
        public long GiftCardNumberFinal { get; set; }
    
        public virtual GiftCardBlockTable GiftCardBlockTable { get; set; }
    }
}
