//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCardBlockLine
    {
        public long GiftCardBlockId { get; set; }
        public int Sequence { get; set; }
        public long GiftCardNumberStart { get; set; }
        public long GiftCardNumberFinal { get; set; }
    
        public virtual GiftCardBlockTable GiftCardBlockTable { get; set; }
    }
}
