//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCardTemplateLine
    {
        public long GiftCardTemplateId { get; set; }
        public int Sequence { get; set; }
        public long ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string StatusLine { get; set; }
    
        public virtual GiftCardTemplateTable GiftCardTemplateTable { get; set; }
        public virtual Product Product { get; set; }
    }
}
