//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalCreditCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalCreditCard()
        {
            this.InternalCreditCardLine = new HashSet<InternalCreditCardLine>();
        }
    
        public long InternalCreditCardId { get; set; }
        public long InternalCreditCardIdLocal { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public System.DateTime Vigence { get; set; }
        public System.DateTime Expiration { get; set; }
        public long EmployeeId { get; set; }
        public decimal Quota { get; set; }
        public decimal Consumed { get; set; }
        public bool Printed { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string Workstation { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalCreditCardLine> InternalCreditCardLine { get; set; }
    }
}
