//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventProductLocation
    {
        public long ProductId { get; set; }
        public int LocationId { get; set; }
        public int InventLocationId { get; set; }
        public decimal MinStock { get; set; }
        public decimal MaxStock { get; set; }
        public decimal Stock { get; set; }
    
        public virtual InventLocation InventLocation { get; set; }
        public virtual Product Product { get; set; }
    }
}
