//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventTransType
    {
        public int InventTransTypeId { get; set; }
        public string Name { get; set; }
        public string SAPCode { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
    }
}
