//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPromotion
    {
        public long OrderId { get; set; }
        public int Sequence { get; set; }
        public long ProductId { get; set; }
        public long PromotionId { get; set; }
        public decimal QuantityReward { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual PromotionTable PromotionTable { get; set; }
    }
}
