//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymMode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymMode()
        {
            this.ClosingCashLine = new HashSet<ClosingCashLine>();
            this.CountCashLine = new HashSet<CountCashLine>();
            this.InvoicePaymMode = new HashSet<InvoicePaymMode>();
            this.OrderPaymMode = new HashSet<OrderPaymMode>();
            this.PromotionPaymMode = new HashSet<PromotionPaymMode>();
        }
    
        public int PaymModeId { get; set; }
        public string Name { get; set; }
        public string SAPCode { get; set; }
        public Nullable<bool> UseWithhold { get; set; }
        public Nullable<bool> UseFinanceSystem { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClosingCashLine> ClosingCashLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountCashLine> CountCashLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePaymMode> InvoicePaymMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPaymMode> OrderPaymMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionPaymMode> PromotionPaymMode { get; set; }
    }
}
