//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalStockCountingLine
    {
        public int PhysicalStockCountingId { get; set; }
        public int Sequence { get; set; }
        public long ProductId { get; set; }
        public int InventUnitId { get; set; }
        public decimal StockQuantity { get; set; }
        public decimal CountedQuantity { get; set; }
        public decimal Cost { get; set; }
    
        public virtual InventUnit InventUnit { get; set; }
        public virtual PhysicalStockCountingTable PhysicalStockCountingTable { get; set; }
        public virtual Product Product { get; set; }
    }
}
