//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InventProductLocation = new HashSet<InventProductLocation>();
            this.ProductBarcode = new HashSet<ProductBarcode>();
            this.GiftCardTemplateLine = new HashSet<GiftCardTemplateLine>();
            this.GiftCardTemplateTable = new HashSet<GiftCardTemplateTable>();
            this.ProductModule = new HashSet<ProductModule>();
            this.InvoiceLine = new HashSet<InvoiceLine>();
            this.SalesOrderLine = new HashSet<SalesOrderLine>();
        }
    
        public long ProductId { get; set; }
        public string SAPCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int InventUnitId { get; set; }
        public int ProductGroupId { get; set; }
        public int ProductCategoryId { get; set; }
        public string Type { get; set; }
        public bool IsDeductible { get; set; }
        public bool UseTax { get; set; }
        public bool UseIrbp { get; set; }
        public bool IsECommerce { get; set; }
        public bool UseCatchWeight { get; set; }
        public decimal CatchWeightMax { get; set; }
        public decimal CatchWeightMin { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string ProductOldCode { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string Workstation { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventProductLocation> InventProductLocation { get; set; }
        public virtual InventUnit InventUnit { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBarcode> ProductBarcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftCardTemplateLine> GiftCardTemplateLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftCardTemplateTable> GiftCardTemplateTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductModule> ProductModule { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderLine> SalesOrderLine { get; set; }
    }
}
