//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionProducts
    {
        public long PromotionId { get; set; }
        public int Sequence { get; set; }
        public string Type { get; set; }
        public string Origin { get; set; }
        public int ProductGroupId { get; set; }
        public int ProductCategoryId { get; set; }
        public long ProductId { get; set; }
        public decimal Percent { get; set; }
        public bool AddCoupon { get; set; }
        public string StatusPromProd { get; set; }
    
        public virtual PromotionTable PromotionTable { get; set; }
    }
}
