//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromotionTable()
        {
            this.ConsumerCardLine = new HashSet<ConsumerCardLine>();
            this.InvoicePromotion = new HashSet<InvoicePromotion>();
            this.OrderPromotion = new HashSet<OrderPromotion>();
            this.PromotionCustomer = new HashSet<PromotionCustomer>();
            this.PromotionPaymMode = new HashSet<PromotionPaymMode>();
            this.PromotionProducts = new HashSet<PromotionProducts>();
            this.PromotionReward = new HashSet<PromotionReward>();
        }
    
        public long PromotionId { get; set; }
        public string Name { get; set; }
        public int PromotionTypeId { get; set; }
        public string ConsumptionOrigin { get; set; }
        public decimal ConsumptionMax { get; set; }
        public System.DateTime Vigence { get; set; }
        public System.DateTime Expiration { get; set; }
        public bool UseMonday { get; set; }
        public bool UseTuesday { get; set; }
        public bool UseWednesday { get; set; }
        public bool UseThursday { get; set; }
        public bool UseFriday { get; set; }
        public bool UseSaturday { get; set; }
        public bool UseSunday { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string Workstation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerCardLine> ConsumerCardLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePromotion> InvoicePromotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPromotion> OrderPromotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionCustomer> PromotionCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionPaymMode> PromotionPaymMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionProducts> PromotionProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionReward> PromotionReward { get; set; }
        public virtual PromotionType PromotionType { get; set; }
    }
}
