//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionReward
    {
        public long PromotionId { get; set; }
        public int Sequence { get; set; }
        public long ProductId { get; set; }
        public decimal StartRange { get; set; }
        public decimal FinalRange { get; set; }
        public decimal Percent { get; set; }
        public bool LowInventory { get; set; }
        public long ProductIdReward { get; set; }
        public int QuantityReceive { get; set; }
        public int MaxReceive { get; set; }
        public string Caption { get; set; }
        public int TotalReward { get; set; }
        public int StockReward { get; set; }
        public string StatusPromRew { get; set; }
    
        public virtual PromotionTable PromotionTable { get; set; }
    }
}
