//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionCustomer
    {
        public long PromotionId { get; set; }
        public int Sequence { get; set; }
        public long CustomerId { get; set; }
        public decimal Percent { get; set; }
        public string StatusPromCust { get; set; }
    
        public virtual PromotionTable PromotionTable { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
