//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLog
    {
        public long SalesLogId { get; set; }
        public short LocationId { get; set; }
        public int EmissionPointId { get; set; }
        public long InvoiceNumber { get; set; }
        public long CustomerId { get; set; }
        public int LogTypeId { get; set; }
        public int ReasonId { get; set; }
        public string Authorization { get; set; }
        public string XmlLog { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string Workstation { get; set; }
    
        public virtual LogType LogType { get; set; }
    }
}
