//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRemissionLine
    {
        public long SalesRemissionId { get; set; }
        public int Sequence { get; set; }
        public long InvoiceId { get; set; }
        public long SalesRemissionNumber { get; set; }
        public string Status { get; set; }
    
        public virtual SalesRemissionTable SalesRemissionTable { get; set; }
        public virtual InvoiceTable InvoiceTable { get; set; }
    }
}
