//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLog
    {
        public long SalesLogId { get; set; }
        public short LocationId { get; set; }
        public int EmissionPointId { get; set; }
        public long InvoiceNumber { get; set; }
        public long CustomerId { get; set; }
        public int LogTypeId { get; set; }
        public int ReasonId { get; set; }
        public string Authorization { get; set; }
        public string XmlLog { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string Workstation { get; set; }
    
        public virtual LogType LogType { get; set; }
    }
}
