//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderPayment
    {
        public long SalesOrderId { get; set; }
        public int Sequence { get; set; }
        public int PaymModeId { get; set; }
        public decimal Amount { get; set; }
        public string Reference { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual PaymMode PaymMode { get; set; }
    }
}
