//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequenceTable
    {
        public short LocationId { get; set; }
        public int SequenceId { get; set; }
        public string SeqType { get; set; }
        public int EmissionPointId { get; set; }
        public int Sequence { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
