//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public int ServerId { get; set; }
        public string Name { get; set; }
        public bool IsCentral { get; set; }
        public bool IsLocal { get; set; }
        public string Status { get; set; }
    }
}
